custom: 
  - "https://tronscan.org/#/address/TUQj3sguQjmKFJEMotyb3kERVgnfvhzG7o" # USDT/USDC (TRC20)
  - "https://solscan.io/account/6VA9oJbkszteTZJbH6mmLioKTSq4r4E3N1bsoPaxQgr4" # SOL
  - "https://xrpscan.com/account/rDkEZehHFqSjiGdBHsseR64fCcRXuJbgfr" # XRP
